[package]
name = "rust_blog"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web 框架 与 异步运行时
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
# 序列化 / 反序列化 (DTO 与 JSON 交互)
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
# 数据库 (SQLx PostgreSQL)
sqlx = { version = "0.9.0", features = [
  "postgres",
  "macros",
  "chrono",
  "uuid",
  "runtime-tokio",
  "tls-rustls",
] }
# 鉴权与安全工具
argon2 = "0.5.3"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }

# HTTP 中间件与日志观察
tower-http = { version = "0.7.0", features = ["compression-full", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# 环境变量与配置加载
dotenvy = "0.15.7"

# 常用数据类型支持
uuid = { version = "1.24.0", features = ["serde", "v4"] }
chrono = { version = "0.4.45", features = ["serde"] }
thiserror = "2.0.19"
async-trait = "0.1.91"
rand = "0.8"
